name: laqya_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  mobile_scanner: ^3.3.0

  lottie: ^2.7.0
  easy_localization: ^3.0.1
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  image_picker: ^1.0.4
  firebase_storage: ^11.5.1
  path_provider: ^2.0.11
  qr_flutter: ^4.0.0
  permission_handler: ^11.3.0
  share_plus: ^7.2.1
  flutter_image_gallery_saver: ^0.0.2
  audioplayers: ^5.2.1
  flutter_slidable: ^3.0.0
  google_maps_flutter: ^2.5.0
  url_launcher: ^6.2.5
  location: ^5.0.3
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^17.0.0
  firebase_app_check: ^0.2.0
  cached_network_image: ^3.2.3




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/logo.jpg
    - assets/images/haram.jpg
    - assets/lottie/loader.json
    - assets/lottie/celebration.json
    - assets/lottie/error.json
    - assets/lottie/success.json
    - assets/translations/
    - assets/fonts/
    - assets/sounds/success.mp3
    - assets/sounds/successb.mp3

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
