final List<Map<String, String>> haramLocations = [
  {'ar': 'صحن الطواف', 'en': 'Tawaf Area'},
  {'ar': 'المسعى', 'en': 'Sa’i Area'},
  {'ar': 'دور الميزانين', 'en': 'Mezzanine Floor'},
  {'ar': 'الدور الأرضي', 'en': 'Ground Floor'},
  {'ar': 'الدور الأول', 'en': 'First Floor'},
  {'ar': 'الدور الثاني', 'en': 'Second Floor'},
  {'ar': 'السقف', 'en': 'Roof'},
  {'ar': 'باب الملك عبدالعزيز', 'en': 'King Abdulaziz Gate'},
  {'ar': 'باب الملك فهد', 'en': 'King Fahd Gate'},
  {'ar': 'باب العمرة', 'en': 'Umrah Gate'},
  {'ar': 'باب المروة', 'en': 'Marwah Gate'},
  {'ar': 'باب السلام', 'en': 'Salam Gate'},
  {'ar': 'الساحة الشمالية', 'en': 'North Square'},
  {'ar': 'الساحة الجنوبية', 'en': 'South Square'},
  {'ar': 'الساحة الغربية', 'en': 'West Square'},
  {'ar': 'الساحة الشرقية', 'en': 'East Square'},
  {'ar': 'بوابات النساء', 'en': 'Women Gates'},
  {'ar': 'دورات المياه - الشمالية', 'en': 'North Toilets'},
  {'ar': 'دورات المياه - الجنوبية', 'en': 'South Toilets'},
  {'ar': 'دورات المياه - الغربية', 'en': 'West Toilets'},
  {'ar': 'المصاعد', 'en': 'Elevators'},
  {'ar': 'السلالم الكهربائية', 'en': 'Escalators'},
  {'ar': 'مكتب المفقودات', 'en': 'Lost & Found Office'},
  {'ar': 'مكتب الأمن', 'en': 'Security Office'},
];
