// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyPqyaM8BPYu_c4mOjRwtw8YNkcZKH03o',
    appId: '1:718210157792:web:cb5745258af9ac9da49485',
    messagingSenderId: '718210157792',
    projectId: 'laqya-app',
    authDomain: 'laqya-app.firebaseapp.com',
    storageBucket: 'laqya-app.firebasestorage.app',
    measurementId: 'G-FG6LLXKXMK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH_lfU5tsAGDOcAL12frlEmuyrRfZPzRw',
    appId: '1:718210157792:android:f5cff39c70984f86a49485',
    messagingSenderId: '718210157792',
    projectId: 'laqya-app',
    storageBucket: 'laqya-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmhU1GDBYtazudjZkInzghYVoI-KojkvQ',
    appId: '1:718210157792:ios:9f5a4481cb57991ca49485',
    messagingSenderId: '718210157792',
    projectId: 'laqya-app',
    storageBucket: 'laqya-app.firebasestorage.app',
    iosBundleId: 'com.example.laqyaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyPqyaM8BPYu_c4mOjRwtw8YNkcZKH03o',
    appId: '1:718210157792:web:210c3bf8b14a04daa49485',
    messagingSenderId: '718210157792',
    projectId: 'laqya-app',
    authDomain: 'laqya-app.firebaseapp.com',
    storageBucket: 'laqya-app.firebasestorage.app',
    measurementId: 'G-0Q8J0BKL2Z',
  );
}
